---
openapi: 3.0.3
info:
  title: Generated API
  version: "1.0"
paths:
  /api/MyDataItemNames:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  type: string
  /api/MyDataItems:
    get:
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyDataItemComposite'
    post:
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyDataItemComposite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
  /api/MyDataItems/{id}:
    get:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
    put:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyDataItemComposite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
    delete:
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
  /api/opi/MyDataItems:
    get:
      operationId: readAllMyDataItemComposites
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MyDataItemComposite'
    post:
      operationId: createMyDataItemComposite
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyDataItemComposite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
  /api/opi/MyDataItems/{id}:
    get:
      operationId: readMyDataItemComposite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
    put:
      operationId: updateMyDataItemComposite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MyDataItemComposite'
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MyDataItemComposite'
    delete:
      operationId: deleteMyDataItemComposite
      parameters:
        - name: id
          in: path
          required: true
          schema:
            format: int64
            type: integer
      responses:
        "200":
          description: OK
          content:
            application/json:
              schema:
                type: boolean
components:
  schemas:
    MyDataItemComposite:
      type: object
      properties:
        id:
          format: int64
          type: integer
        parts:
          uniqueItems: true
          type: array
          items:
            $ref: '#/components/schemas/MyDataItemPart'
        name:
          type: string
    MyDataItemPart:
      type: object
      properties:
        id:
          format: int64
          type: integer
        name:
          type: string
